### ISSUE TITLE
Wrong calculation when html font-size set with calc

### ISSUE THREAD

**Issue by Tabrisrp** [robwierzbowski/node-pixrem#28]
Hello,

I'm using a CSS framework (KNACSS) that defines the base font size in the html like this :

> font-size:62.5%;
> font-size:calc(.625em);

When running pixrem, the resulting font-sizes in pixels are off. Here are some examples : 

> h1,.h1-like{
>    font-size:72px;
>   font-size:3rem;
> }
> h2,.h2-like{
>    font-size:57px;
>    font-size:2.4rem;
> }

As yo can see, the pixel sizes should be 30px and 24px, since the html is defining a base font-size of 10px (16x0,625).

I'm not really used to node and all the things around, so if I'm missing something, and it's not a bug, please tell me :)

**Comment by iamvdo** [comment]
It should be fixed now. I also added an option to disable root font-size detection, if needed.
Thanks for reporting.

**Comment by Tabrisrp** [comment]
Here is an extract of my css declaring html and body font-size (default one from KNACSS)

```
html{
font-size:62.5%;
font-size:-webkit-calc(.625em);
font-size:calc(.625em);
-webkit-text-size-adjust:100%;
-ms-text-size-adjust:100%
}

body{font-size:1.5em;
font-family:'Open sans',sans-serif;
line-height:1.5
}
```

At the moment, my initial problem is still there

**Comment by iamvdo** [comment]
Can't reproduce.
Plus, when I copy/paste knacss.css in http://pleeease.io/play, there is no problem, we get:
```css
h1,
.h1-like {
  font-size: 32px;
  font-size: 3.2rem;
}
```
Your problem lies elsewhere...

**Comment by Tabrisrp** [comment]
OK, but copy/pasting http://knacss.com/css/knacss-unminified.css in http://pleeease.io/play gets me the following, with default settings :

![pleeease-play-knacss](https://cloud.githubusercontent.com/assets/3465180/6868650/9c399d76-d48d-11e4-9504-c10bf18e8434.png)

How can we have different results for the same file ?

**Comment by iamvdo** [comment]
OK, found bug.
Release patch in 1.2.2

File here http://knacss.com/css/knacss-unminified.css is not the same as https://github.com/raphaelgoetter/KNACSS/blob/master/css/knacss-unminified.css

In the former, selectors rules like 

```css
:root [class*="autogrid"] > * {
  /* fallback for Opera Mini */
  font-size: 14px;
  font-size: 1.4rem;
}
```

gaves wrong font-size detection. Regex was wrong :/

**Comment by Tabrisrp** [comment]
Great, yes the knacss version on github is the beta one, and the v4 changes a lot in things in the declarations for the grids.

Anyway, good thing the bug was identified, well done !

**Comment by iamvdo** [comment]
Yep, I see version number after.
Thanks for reporting. :)

**Comment by Tabrisrp** [comment]
No problem, just tried with the new version, and it works perfectly
